apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: hooks-2
  namespace: codefresh
spec:
  project: default  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/pasha-codefresh/argocd-personal-examples
    targetRevision: main
    path: hooks/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
